import AppKit
import Foundation
import Testing
@testable import NotchToolbox

@MainActor
struct ClipboardModuleTests {

    @Test func liveClientExcludesWebURLsFromFileURLs() {
        let pasteboard = NSPasteboard.withUniqueName()
        pasteboard.clearContents()
        pasteboard.writeObjects([URL(string: "https://example.com/page")! as NSURL])

        let client = LiveClipboardPasteboardClient(pasteboard: pasteboard)

        #expect(client.snapshot().fileURLs.isEmpty)
    }

    @Test func liveClientKeepsRealFileURLs() throws {
        let fileURL = FileManager.default.temporaryDirectory
            .appending(path: "\(UUID().uuidString).txt")
        try Data("hello".utf8).write(to: fileURL)
        defer { try? FileManager.default.removeItem(at: fileURL) }

        let pasteboard = NSPasteboard.withUniqueName()
        pasteboard.clearContents()
        pasteboard.writeObjects([fileURL as NSURL])

        let client = LiveClipboardPasteboardClient(pasteboard: pasteboard)

        #expect(
            client.snapshot().fileURLs.map(\.lastPathComponent)
                .contains(fileURL.lastPathComponent)
        )
    }

    @Test func normalizerCreatesSecurityScopedFileReferenceBookmarks() throws {
        let fileURL = FileManager.default.temporaryDirectory
            .appending(path: "\(UUID().uuidString).txt")
        try Data("hello".utf8).write(to: fileURL)
        defer { try? FileManager.default.removeItem(at: fileURL) }

        let snapshot = ClipboardPasteboardSnapshot(
            changeCount: 1,
            availableTypes: [],
            dataByType: [:],
            fileURLs: [fileURL]
        )
        let capture = try #require(
            try ClipboardNormalizer().normalize(snapshot: snapshot, sourceApp: nil)
        )
        guard case let .fileReferences(references) = capture.payload else {
            Issue.record("expected file references payload")
            return
        }

        // Only a security-scoped bookmark resolves with .withSecurityScope; a plain
        // (.minimalBookmark) one throws NSCocoaError 259, resolving to nil.
        var isStale = false
        let resolvedScoped = try? URL(
            resolvingBookmarkData: references[0].bookmarkData,
            options: [.withSecurityScope],
            relativeTo: nil,
            bookmarkDataIsStale: &isStale
        )
        #expect(resolvedScoped != nil)
    }

    @Test func referenceValidatorResolvesLegacyPlainBookmarks() throws {
        let fileURL = FileManager.default.temporaryDirectory
            .appending(path: "\(UUID().uuidString).txt")
        try Data("legacy".utf8).write(to: fileURL)
        defer { try? FileManager.default.removeItem(at: fileURL) }

        // Simulate a history.json entry written by the pre-upgrade build, which
        // used .minimalBookmark (a plain, non-scoped bookmark).
        let legacyReference = ClipboardFileReference(
            fileName: fileURL.lastPathComponent,
            isDirectory: false,
            bookmarkData: try fileURL.bookmarkData(
                options: .minimalBookmark,
                includingResourceValuesForKeys: nil,
                relativeTo: nil
            )
        )

        let resolved = try ClipboardReferenceValidator().validate([legacyReference])

        #expect(resolved.count == 1)
        #expect(resolved[0].resolvingSymlinksInPath() == fileURL.resolvingSymlinksInPath())
    }

    @Test func normalizerDropsPasswordManagerConcealedContent() throws {
        let snapshot = ClipboardPasteboardSnapshot(
            changeCount: 1,
            availableTypes: ["org.nspasteboard.ConcealedType", "public.utf8-plain-text"],
            dataByType: ["public.utf8-plain-text": Data("hunter2".utf8)],
            fileURLs: []
        )

        let capture = try ClipboardNormalizer().normalize(snapshot: snapshot, sourceApp: nil)

        #expect(capture == nil)
    }

    @Test func normalizerDropsTransientAndAutoGeneratedContent() throws {
        for excludedType in ["org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType"] {
            let snapshot = ClipboardPasteboardSnapshot(
                changeCount: 1,
                availableTypes: [excludedType, "public.utf8-plain-text"],
                dataByType: ["public.utf8-plain-text": Data("otp-123456".utf8)],
                fileURLs: []
            )

            #expect(try ClipboardNormalizer().normalize(snapshot: snapshot, sourceApp: nil) == nil)
        }
    }

    @Test func imageCaptureContentHashIsCompactNotFullPayload() throws {
        let bigData = Data(repeating: 0xAB, count: 100_000)
        let snapshot = ClipboardPasteboardSnapshot(
            changeCount: 1,
            availableTypes: ["public.png"],
            dataByType: ["public.png": bigData],
            fileURLs: []
        )

        let capture = try #require(
            try ClipboardNormalizer().normalize(snapshot: snapshot, sourceApp: nil)
        )

        #expect(capture.contentType == .image)
        // A real hash is a fixed short fingerprint; the previous implementation
        // embedded the entire base64 payload (~133 KB for this input).
        #expect(capture.contentHash.count < 200)
    }

    @Test func imageContentHashIsStableAndDataDependent() throws {
        func hash(for bytes: [UInt8]) throws -> String {
            let snapshot = ClipboardPasteboardSnapshot(
                changeCount: 1,
                availableTypes: ["public.png"],
                dataByType: ["public.png": Data(bytes)],
                fileURLs: []
            )
            return try #require(
                try ClipboardNormalizer().normalize(snapshot: snapshot, sourceApp: nil)
            ).contentHash
        }

        #expect(try hash(for: [1, 2, 3, 4]) == hash(for: [1, 2, 3, 4]))
        #expect(try hash(for: [1, 2, 3, 4]) != hash(for: [9, 9, 9, 9]))
    }

    @Test func normalizerSkipsOversizedImagePayload() throws {
        let normalizer = ClipboardNormalizer(maxInlinePayloadBytes: 1024)
        let snapshot = ClipboardPasteboardSnapshot(
            changeCount: 1,
            availableTypes: ["public.png"],
            dataByType: ["public.png": Data(repeating: 0xAB, count: 2048)],
            fileURLs: []
        )

        #expect(try normalizer.normalize(snapshot: snapshot, sourceApp: nil) == nil)
    }

    @Test func normalizerFallsBackToSmallerRepresentationWhenPreferredIsOversized() throws {
        let normalizer = ClipboardNormalizer(maxInlinePayloadBytes: 1024)
        let snapshot = ClipboardPasteboardSnapshot(
            changeCount: 1,
            availableTypes: ["public.tiff", "public.png"],
            dataByType: [
                "public.tiff": Data(repeating: 0xAB, count: 4096),
                "public.png": Data(repeating: 0xCD, count: 512),
            ],
            fileURLs: []
        )

        let capture = try #require(
            try normalizer.normalize(snapshot: snapshot, sourceApp: nil)
        )

        #expect(capture.contentType == .image)
        guard case let .inline(data, pasteboardType, _) = capture.payload else {
            Issue.record("Expected inline payload, got \(capture.payload)")
            return
        }
        #expect(pasteboardType == "public.png")
        #expect(data.count == 512)
    }

    @Test func normalizerSkipsOversizedPlainText() throws {
        let normalizer = ClipboardNormalizer(maxInlinePayloadBytes: 16)
        let snapshot = ClipboardPasteboardSnapshot(
            changeCount: 1,
            availableTypes: ["public.utf8-plain-text"],
            dataByType: [
                "public.utf8-plain-text": Data(repeating: 0x61, count: 64),
            ],
            fileURLs: []
        )

        #expect(try normalizer.normalize(snapshot: snapshot, sourceApp: nil) == nil)
    }

    @Test func liveClientDropsOversizedRepresentationData() {
        let pasteboard = NSPasteboard.withUniqueName()
        pasteboard.clearContents()
        let item = NSPasteboardItem()
        item.setData(
            Data(repeating: 0xAB, count: 2048),
            forType: NSPasteboard.PasteboardType("com.notch.test.blob")
        )
        item.setString("hello", forType: .string)
        pasteboard.writeObjects([item])

        let client = LiveClipboardPasteboardClient(
            pasteboard: pasteboard,
            maxInlinePayloadBytes: 1024
        )
        let snapshot = client.snapshot()

        // The oversized representation is dropped from memory, the small one and
        // the full type list are kept.
        #expect(snapshot.dataByType["com.notch.test.blob"] == nil)
        #expect(snapshot.dataByType["public.utf8-plain-text"] != nil)
        #expect(snapshot.availableTypes.contains("com.notch.test.blob"))
    }

    @Test func storePersistsHistoryAndPayloads() throws {
        let root = try Self.makeTemporaryRoot()
        let fileStore = LocalFileStore(baseURL: root)
        let settingsStore = try SettingsStore(
            storageURL: root.appending(path: "Settings/settings.json")
        )
        let store = try ClipboardStore(
            fileStore: fileStore)
        let capture = ClipboardCapture(
            contentType: .plainText,
            previewText: "hello",
            contentHash: "hash-plain-1",
            capturedAt: Date(timeIntervalSince1970: 10),
            sourceAppBundleID: "com.apple.TextEdit",
            sourceAppName: "TextEdit",
            payload: .inline(
                data: Data("hello".utf8),
                pasteboardType: "public.utf8-plain-text",
                suggestedFileExtension: "txt"
            )
        )

        let history = try store.save(capture, maxItems: 20)
        let reloaded = try store.loadHistory()

        #expect(history.count == 1)
        #expect(reloaded.map(\.contentHash) == ["hash-plain-1"])
        #expect(try store.payloadData(for: reloaded[0]) == Data("hello".utf8))
    }

    @Test func storeTrimsOldItemsWhenMaxItemsDrops() throws {
        let root = try Self.makeTemporaryRoot()
        let fileStore = LocalFileStore(baseURL: root)
        let settingsStore = try SettingsStore(
            storageURL: root.appending(path: "Settings/settings.json")
        )
        let store = try ClipboardStore(
            fileStore: fileStore)

        for index in 0 ..< 3 {
            _ = try store.save(
                ClipboardCapture(
                    contentType: .plainText,
                    previewText: "item-\(index)",
                    contentHash: "hash-\(index)",
                    capturedAt: Date(timeIntervalSince1970: TimeInterval(index)),
                    sourceAppBundleID: nil,
                    sourceAppName: nil,
                    payload: .inline(
                        data: Data("item-\(index)".utf8),
                        pasteboardType: "public.utf8-plain-text",
                        suggestedFileExtension: "txt"
                    )
                ),
                maxItems: 2
            )
        }

        let history = try store.loadHistory()
        #expect(history.map(\.contentHash) == ["hash-2", "hash-1"])
    }

    @Test func storeMovesDuplicateCaptureToFrontInsteadOfAppending() throws {
        let root = try Self.makeTemporaryRoot()
        let fileStore = LocalFileStore(baseURL: root)
        let settingsStore = try SettingsStore(
            storageURL: root.appending(path: "Settings/settings.json")
        )
        let store = try ClipboardStore(
            fileStore: fileStore)

        _ = try store.save(
            ClipboardCapture(
                contentType: .plainText,
                previewText: "first",
                contentHash: "same-hash",
                capturedAt: Date(timeIntervalSince1970: 1),
                sourceAppBundleID: nil,
                sourceAppName: nil,
                payload: .inline(
                    data: Data("first".utf8),
                    pasteboardType: "public.utf8-plain-text",
                    suggestedFileExtension: "txt"
                )
            ),
            maxItems: 10
        )

        let history = try store.save(
            ClipboardCapture(
                contentType: .plainText,
                previewText: "first",
                contentHash: "same-hash",
                capturedAt: Date(timeIntervalSince1970: 2),
                sourceAppBundleID: nil,
                sourceAppName: nil,
                payload: .inline(
                    data: Data("first".utf8),
                    pasteboardType: "public.utf8-plain-text",
                    suggestedFileExtension: "txt"
                )
            ),
            maxItems: 10
        )

        #expect(history.count == 1)
        #expect(history[0].copiedAt == Date(timeIntervalSince1970: 2))
    }

    @Test func storePersistsThumbnailDescriptorAndSnapshotFile() throws {
        let root = try Self.makeTemporaryRoot()
        let fileStore = LocalFileStore(baseURL: root)
        let settingsStore = try SettingsStore(
            storageURL: root.appending(path: "Settings/settings.json")
        )
        let store = try ClipboardStore(fileStore: fileStore)
        let thumbnailData = Data([0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A])
        let thumbnailDescriptor = ClipboardThumbnailDescriptor(
            fileName: "image-preview.png",
            pixelWidth: 160,
            pixelHeight: 120,
            kind: .imagePreview
        )

        let history = try store.save(
            ClipboardCapture(
                contentType: .image,
                previewText: "Image",
                contentHash: "image-hash",
                capturedAt: Date(timeIntervalSince1970: 30),
                sourceAppBundleID: nil,
                sourceAppName: nil,
                payload: .inline(
                    data: Data([0x89, 0x50, 0x4E, 0x47]),
                    pasteboardType: "public.png",
                    suggestedFileExtension: "png"
                ),
                thumbnail: ClipboardThumbnailSnapshot(
                    data: thumbnailData,
                    descriptor: thumbnailDescriptor
                )
            ),
            maxItems: 10
        )
        let reloaded = try store.loadHistory()
        let storedDescriptor = try #require(history.first?.thumbnail)
        let reloadedDescriptor = try #require(reloaded.first?.thumbnail)
        let thumbnailURL = fileStore.url(for: .clipboardThumbnails).appending(
            path: storedDescriptor.fileName
        )

        #expect(history.count == 1)
        #expect(storedDescriptor.kind == thumbnailDescriptor.kind)
        #expect(storedDescriptor.pixelWidth == thumbnailDescriptor.pixelWidth)
        #expect(storedDescriptor.pixelHeight == thumbnailDescriptor.pixelHeight)
        #expect(storedDescriptor.fileName.hasSuffix(".png"))
        #expect(storedDescriptor.fileName != thumbnailDescriptor.fileName)
        #expect(reloaded.count == 1)
        #expect(reloadedDescriptor == storedDescriptor)
        #expect(try Data(contentsOf: thumbnailURL) == thumbnailData)
    }

    @Test func storeTrimmingRemovesOrphanThumbnailFiles() throws {
        let root = try Self.makeTemporaryRoot()
        let fileStore = LocalFileStore(baseURL: root)
        let settingsStore = try SettingsStore(
            storageURL: root.appending(path: "Settings/settings.json")
        )
        let store = try ClipboardStore(fileStore: fileStore)

        let firstHistory = try store.save(
            ClipboardCapture(
                contentType: .image,
                previewText: "first",
                contentHash: "first-image-hash",
                capturedAt: Date(timeIntervalSince1970: 1),
                sourceAppBundleID: nil,
                sourceAppName: nil,
                payload: .inline(
                    data: Data([0x01]),
                    pasteboardType: "public.png",
                    suggestedFileExtension: "png"
                ),
                thumbnail: ClipboardThumbnailSnapshot(
                    data: Data([0x11, 0x12]),
                    descriptor: ClipboardThumbnailDescriptor(
                        fileName: "first-thumbnail.png",
                        pixelWidth: 80,
                        pixelHeight: 80,
                        kind: .imagePreview
                    )
                )
            ),
            maxItems: 2
        )
        let firstThumbnailURL: URL
        if let thumbnail = firstHistory[0].thumbnail {
            firstThumbnailURL = fileStore.url(for: .clipboardThumbnails).appending(
                path: thumbnail.fileName
            )
        } else {
            Issue.record("Expected first history item to have thumbnail metadata")
            return
        }

        _ = try store.save(
            ClipboardCapture(
                contentType: .plainText,
                previewText: "second",
                contentHash: "second-hash",
                capturedAt: Date(timeIntervalSince1970: 2),
                sourceAppBundleID: nil,
                sourceAppName: nil,
                payload: .inline(
                    data: Data("second".utf8),
                    pasteboardType: "public.utf8-plain-text",
                    suggestedFileExtension: "txt"
                )
            ),
            maxItems: 2
        )

        let history = try store.save(
            ClipboardCapture(
                contentType: .plainText,
                previewText: "third",
                contentHash: "third-hash",
                capturedAt: Date(timeIntervalSince1970: 3),
                sourceAppBundleID: nil,
                sourceAppName: nil,
                payload: .inline(
                    data: Data("third".utf8),
                    pasteboardType: "public.utf8-plain-text",
                    suggestedFileExtension: "txt"
                )
            ),
            maxItems: 2
        )

        #expect(history.map(\.contentHash) == ["third-hash", "second-hash"])
        #expect(FileManager.default.fileExists(atPath: firstThumbnailURL.path(percentEncoded: false)) == false)
    }

    @Test func storeDuplicateReplacementRemovesOrphanThumbnailFile() throws {
        let root = try Self.makeTemporaryRoot()
        let fileStore = LocalFileStore(baseURL: root)
        let settingsStore = try SettingsStore(
            storageURL: root.appending(path: "Settings/settings.json")
        )
        let store = try ClipboardStore(fileStore: fileStore)

        let first = try store.save(
            ClipboardCapture(
                contentType: .image,
                previewText: "same",
                contentHash: "same-image-hash",
                capturedAt: Date(timeIntervalSince1970: 1),
                sourceAppBundleID: nil,
                sourceAppName: nil,
                payload: .inline(
                    data: Data([0x01]),
                    pasteboardType: "public.png",
                    suggestedFileExtension: "png"
                ),
                thumbnail: ClipboardThumbnailSnapshot(
                    data: Data([0x11, 0x12]),
                    descriptor: ClipboardThumbnailDescriptor(
                        fileName: "duplicate-thumbnail.png",
                        pixelWidth: 80,
                        pixelHeight: 80,
                        kind: .imagePreview
                    )
                )
            ),
            maxItems: 10
        )
        let firstThumbnailURL = fileStore.url(for: .clipboardThumbnails).appending(
            path: try #require(first.first?.thumbnail?.fileName)
        )

        let replacement = try store.save(
            ClipboardCapture(
                contentType: .image,
                previewText: "same",
                contentHash: "same-image-hash",
                capturedAt: Date(timeIntervalSince1970: 2),
                sourceAppBundleID: nil,
                sourceAppName: nil,
                payload: .inline(
                    data: Data([0x02]),
                    pasteboardType: "public.png",
                    suggestedFileExtension: "png"
                ),
                thumbnail: ClipboardThumbnailSnapshot(
                    data: Data([0x21, 0x22]),
                    descriptor: ClipboardThumbnailDescriptor(
                        fileName: "duplicate-thumbnail.png",
                        pixelWidth: 96,
                        pixelHeight: 96,
                        kind: .imagePreview
                    )
                )
            ),
            maxItems: 10
        )

        let replacementThumbnail = try #require(replacement.first?.thumbnail)
        #expect(replacement.count == 1)
        #expect(FileManager.default.fileExists(atPath: firstThumbnailURL.path(percentEncoded: false)) == false)
        #expect(replacementThumbnail.fileName.hasSuffix(".png"))
        #expect(replacementThumbnail.fileName != "duplicate-thumbnail.png")
    }

    @Test func storeReplaceHistoryRemovesOrphanThumbnailFiles() throws {
        let root = try Self.makeTemporaryRoot()
        let fileStore = LocalFileStore(baseURL: root)
        let settingsStore = try SettingsStore(
            storageURL: root.appending(path: "Settings/settings.json")
        )
        let store = try ClipboardStore(fileStore: fileStore)

        let first = try store.save(
            ClipboardCapture(
                contentType: .image,
                previewText: "first",
                contentHash: "first-image-hash",
                capturedAt: Date(timeIntervalSince1970: 10),
                sourceAppBundleID: nil,
                sourceAppName: nil,
                payload: .inline(
                    data: Data([0x21]),
                    pasteboardType: "public.png",
                    suggestedFileExtension: "png"
                ),
                thumbnail: ClipboardThumbnailSnapshot(
                    data: Data([0x31, 0x32]),
                    descriptor: ClipboardThumbnailDescriptor(
                        fileName: "replace-first-thumbnail.png",
                        pixelWidth: 48,
                        pixelHeight: 48,
                        kind: .imagePreview
                    )
                )
            ),
            maxItems: 10
        )
        let history = try store.save(
            ClipboardCapture(
                contentType: .file,
                previewText: "folder",
                contentHash: "folder-hash",
                capturedAt: Date(timeIntervalSince1970: 20),
                sourceAppBundleID: nil,
                sourceAppName: nil,
                payload: .fileReferences([]),
                thumbnail: ClipboardThumbnailSnapshot(
                    data: Data([0x41, 0x42]),
                    descriptor: ClipboardThumbnailDescriptor(
                        fileName: "replace-second-thumbnail.png",
                        pixelWidth: 64,
                        pixelHeight: 64,
                        kind: .folderPreview
                    )
                )
            ),
            maxItems: 10
        )
        let orphanThumbnailURL: URL
        if let thumbnail = first[0].thumbnail {
            orphanThumbnailURL = fileStore.url(for: .clipboardThumbnails).appending(
                path: thumbnail.fileName
            )
        } else {
            Issue.record("Expected first saved item to have thumbnail metadata")
            return
        }

        let replaced = try store.replaceHistory([history[0]])

        #expect(replaced.count == 1)
        #expect(replaced[0].contentHash == "folder-hash")
        #expect(FileManager.default.fileExists(atPath: orphanThumbnailURL.path(percentEncoded: false)) == false)
    }

    @Test func storeGeneratesUniqueThumbnailFileNamesForRepeatedDescriptorNames() throws {
        let root = try Self.makeTemporaryRoot()
        let fileStore = LocalFileStore(baseURL: root)
        let settingsStore = try SettingsStore(
            storageURL: root.appending(path: "Settings/settings.json")
        )
        let store = try ClipboardStore(fileStore: fileStore)

        let first = try store.save(
            ClipboardCapture(
                contentType: .image,
                previewText: "first",
                contentHash: "first-unique-thumbnail",
                capturedAt: Date(timeIntervalSince1970: 1),
                sourceAppBundleID: nil,
                sourceAppName: nil,
                payload: .inline(
                    data: Data([0x01]),
                    pasteboardType: "public.png",
                    suggestedFileExtension: "png"
                ),
                thumbnail: ClipboardThumbnailSnapshot(
                    data: Data([0x31]),
                    descriptor: ClipboardThumbnailDescriptor(
                        fileName: "shared-name.png",
                        pixelWidth: 80,
                        pixelHeight: 80,
                        kind: .imagePreview
                    )
                )
            ),
            maxItems: 10
        )
        let second = try store.save(
            ClipboardCapture(
                contentType: .image,
                previewText: "second",
                contentHash: "second-unique-thumbnail",
                capturedAt: Date(timeIntervalSince1970: 2),
                sourceAppBundleID: nil,
                sourceAppName: nil,
                payload: .inline(
                    data: Data([0x02]),
                    pasteboardType: "public.png",
                    suggestedFileExtension: "png"
                ),
                thumbnail: ClipboardThumbnailSnapshot(
                    data: Data([0x32]),
                    descriptor: ClipboardThumbnailDescriptor(
                        fileName: "shared-name.png",
                        pixelWidth: 96,
                        pixelHeight: 96,
                        kind: .imagePreview
                    )
                )
            ),
            maxItems: 10
        )

        let firstFileName = try #require(first.last?.thumbnail?.fileName)
        let secondFileName = try #require(second.first?.thumbnail?.fileName)

        #expect(firstFileName != secondFileName)
        #expect(FileManager.default.fileExists(atPath: fileStore.url(for: .clipboardThumbnails).appending(path: firstFileName).path(percentEncoded: false)))
        #expect(FileManager.default.fileExists(atPath: fileStore.url(for: .clipboardThumbnails).appending(path: secondFileName).path(percentEncoded: false)))
    }

    @Test func normalizerPrefersRichTextOverPlainTextFallback() throws {
        let normalizer = ClipboardNormalizer()
        let snapshot = ClipboardPasteboardSnapshot(
            changeCount: 10,
            availableTypes: ["public.rtf", "public.utf8-plain-text"],
            dataByType: [
                "public.rtf": Data("{\\rtf1\\ansi Hello}".utf8),
                "public.utf8-plain-text": Data("Hello".utf8),
            ],
            fileURLs: []
        )

        let optionalCapture = try normalizer.normalize(
            snapshot: snapshot,
            sourceApp: ClipboardSourceApplication(
                bundleID: "com.apple.TextEdit",
                name: "TextEdit"
            )
        )
        let capture = try #require(optionalCapture)

        #expect(capture.contentType == .richText)
        #expect(capture.previewText == "Hello")
    }

    @Test func normalizerConvertsHTMLOnlyClipboardIntoRTFPayload() throws {
        let normalizer = ClipboardNormalizer()
        let html = "<p><strong>Hello</strong> clipboard</p>"
        let snapshot = ClipboardPasteboardSnapshot(
            changeCount: 10,
            availableTypes: ["public.html"],
            dataByType: ["public.html": Data(html.utf8)],
            fileURLs: []
        )

        let optionalCapture = try normalizer.normalize(snapshot: snapshot, sourceApp: nil)
        let capture = try #require(optionalCapture)

        #expect(capture.contentType == .richText)
        #expect(capture.previewText == "Hello clipboard")

        guard case let .inline(data, pasteboardType, suggestedFileExtension) = capture.payload else {
            Issue.record("Expected inline rich text payload")
            return
        }

        #expect(pasteboardType == "public.rtf")
        #expect(suggestedFileExtension == "rtf")

        let attributedString = try NSAttributedString(
            data: data,
            options: [.documentType: NSAttributedString.DocumentType.rtf],
            documentAttributes: nil
        )
        #expect(attributedString.string.trimmingCharacters(in: .whitespacesAndNewlines) == "Hello clipboard")
    }

    @Test func normalizerDetectsFigmaGraphicFromHTMLRepresentations() throws {
        let normalizer = ClipboardNormalizer()
        let html = Data("<span data-meta=\"figma graphic\"></span>".utf8)
        let token = Data("rfh-token".utf8)
        let sourceURL = Data("https://www.figma.com/file/123".utf8)
        let snapshot = ClipboardPasteboardSnapshot(
            changeCount: 14,
            availableTypes: [
                "public.html",
                "Apple HTML pasteboard type",
                "org.chromium.internal.source-rfh-token",
                "org.chromium.source-url",
            ],
            dataByType: [
                "public.html": html,
                "Apple HTML pasteboard type": html,
                "org.chromium.internal.source-rfh-token": token,
                "org.chromium.source-url": sourceURL,
            ],
            fileURLs: []
        )

        let optionalCapture = try normalizer.normalize(snapshot: snapshot, sourceApp: nil)
        let capture = try #require(optionalCapture)

        #expect(capture.contentType == .figmaGraphic)
        #expect(capture.previewText == "Figma Graphic")

        guard case let .figma(payload) = capture.payload else {
            Issue.record("Expected figma payload")
            return
        }

        #expect(payload.representations.map(\.pasteboardType) == snapshot.availableTypes)
    }

    @Test func normalizerDetectsFigmaTextWhenPlainTextRepresentationExists() throws {
        let normalizer = ClipboardNormalizer()
        let html = Data("<span data-meta=\"figma text\"></span>".utf8)
        let plainText = Data("Button".utf8)
        let token = Data("rfh-token".utf8)
        let sourceURL = Data("https://www.figma.com/file/123".utf8)
        let snapshot = ClipboardPasteboardSnapshot(
            changeCount: 15,
            availableTypes: [
                "public.html",
                "Apple HTML pasteboard type",
                "public.utf8-plain-text",
                "NSStringPboardType",
                "org.chromium.internal.source-rfh-token",
                "org.chromium.source-url",
            ],
            dataByType: [
                "public.html": html,
                "Apple HTML pasteboard type": html,
                "public.utf8-plain-text": plainText,
                "NSStringPboardType": plainText,
                "org.chromium.internal.source-rfh-token": token,
                "org.chromium.source-url": sourceURL,
            ],
            fileURLs: []
        )

        let optionalCapture = try normalizer.normalize(snapshot: snapshot, sourceApp: nil)
        let capture = try #require(optionalCapture)

        #expect(capture.contentType == .figmaText)
        #expect(capture.previewText == "Button")

        guard case let .figma(payload) = capture.payload else {
            Issue.record("Expected figma payload")
            return
        }

        #expect(payload.representations.map(\.pasteboardType) == snapshot.availableTypes)
    }

    @Test func normalizerDoesNotMisclassifyGenericChromiumHTMLAsFigma() throws {
        let normalizer = ClipboardNormalizer()
        let html = Data("<p>figma tips and tricks</p>".utf8)
        let token = Data("rfh-token".utf8)
        let sourceURL = Data("https://www.figma.com/blog".utf8)
        let snapshot = ClipboardPasteboardSnapshot(
            changeCount: 19,
            availableTypes: [
                "public.html",
                "Apple HTML pasteboard type",
                "org.chromium.internal.source-rfh-token",
                "org.chromium.source-url",
            ],
            dataByType: [
                "public.html": html,
                "Apple HTML pasteboard type": html,
                "org.chromium.internal.source-rfh-token": token,
                "org.chromium.source-url": sourceURL,
            ],
            fileURLs: []
        )

        let optionalCapture = try normalizer.normalize(snapshot: snapshot, sourceApp: nil)
        let capture = try #require(optionalCapture)

        #expect(capture.contentType == .richText)
        #expect(capture.previewText == "figma tips and tricks")
    }

    @Test func normalizerDetectsFilesAndDirectoriesFromFileURLs() throws {
        let root = try Self.makeTemporaryRoot()
        let fileURL = root.appending(path: "a.txt")
        let folderURL = root.appending(path: "folder", directoryHint: .isDirectory)
        try Data("a".utf8).write(to: fileURL)
        try FileManager.default.createDirectory(at: folderURL, withIntermediateDirectories: true)
        let normalizer = ClipboardNormalizer()
        let snapshot = ClipboardPasteboardSnapshot(
            changeCount: 11,
            availableTypes: ["public.file-url"],
            dataByType: [:],
            fileURLs: [fileURL, folderURL]
        )

        let optionalCapture = try normalizer.normalize(snapshot: snapshot, sourceApp: nil)
        let capture = try #require(optionalCapture)
        #expect(capture.contentType == .file)

        guard case let .fileReferences(references) = capture.payload else {
            Issue.record("Expected fileReferences payload")
            return
        }

        #expect(references.map(\.fileName) == ["a.txt", "folder"])
        #expect(references.map(\.isDirectory) == [false, true])
    }

    @Test func normalizerDetectsStandardSVGAndPreservesOriginalType() throws {
        let normalizer = ClipboardNormalizer()
        let svgData = Data(#"<svg xmlns="http://www.w3.org/2000/svg"><rect width="12" height="12"/></svg>"#.utf8)
        let snapshot = ClipboardPasteboardSnapshot(
            changeCount: 12,
            availableTypes: ["public.svg-image"],
            dataByType: ["public.svg-image": svgData],
            fileURLs: []
        )

        let optionalCapture = try normalizer.normalize(snapshot: snapshot, sourceApp: nil)
        let capture = try #require(optionalCapture)

        #expect(capture.contentType == .svg)

        guard case let .inline(data, pasteboardType, suggestedFileExtension) = capture.payload else {
            Issue.record("Expected inline SVG payload")
            return
        }

        #expect(data == svgData)
        #expect(pasteboardType == "public.svg-image")
        #expect(suggestedFileExtension == "svg")
    }

    @Test func normalizerPreservesOriginalImageRepresentation() throws {
        let normalizer = ClipboardNormalizer()
        let pngData = Data([0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A])
        let snapshot = ClipboardPasteboardSnapshot(
            changeCount: 13,
            availableTypes: ["public.png"],
            dataByType: ["public.png": pngData],
            fileURLs: []
        )

        let optionalCapture = try normalizer.normalize(snapshot: snapshot, sourceApp: nil)
        let capture = try #require(optionalCapture)

        #expect(capture.contentType == .image)

        guard case let .inline(data, pasteboardType, suggestedFileExtension) = capture.payload else {
            Issue.record("Expected inline image payload")
            return
        }

        #expect(data == pngData)
        #expect(pasteboardType == "public.png")
        #expect(suggestedFileExtension == "png")
    }

    @Test func normalizerAttachesThumbnailSnapshotForInlineImage() throws {
        let normalizer = ClipboardNormalizer()
        let pngData = try #require(Self.makePNGData(size: NSSize(width: 8, height: 6)))
        let snapshot = ClipboardPasteboardSnapshot(
            changeCount: 16,
            availableTypes: ["public.png"],
            dataByType: ["public.png": pngData],
            fileURLs: []
        )

        let optionalCapture = try normalizer.normalize(snapshot: snapshot, sourceApp: nil)
        let capture = try #require(optionalCapture)
        let thumbnail = try #require(capture.thumbnail)

        #expect(capture.contentType == .image)
        #expect(thumbnail.descriptor.kind == .imagePreview)
        #expect(thumbnail.descriptor.fileName.hasSuffix(".png"))
        #expect(thumbnail.descriptor.pixelWidth > 0)
        #expect(thumbnail.descriptor.pixelHeight > 0)
        #expect(thumbnail.data.isEmpty == false)
    }

    @Test func normalizerAttachesFileThumbnailSnapshotForFileReferences() throws {
        let root = try Self.makeTemporaryRoot()
        let fileURL = root.appending(path: "document.txt")
        try Data("document".utf8).write(to: fileURL)
        let normalizer = ClipboardNormalizer()
        let snapshot = ClipboardPasteboardSnapshot(
            changeCount: 17,
            availableTypes: ["public.file-url"],
            dataByType: [:],
            fileURLs: [fileURL]
        )

        let optionalCapture = try normalizer.normalize(snapshot: snapshot, sourceApp: nil)
        let capture = try #require(optionalCapture)
        let thumbnail = try #require(capture.thumbnail)

        #expect(capture.contentType == .file)
        #expect(thumbnail.descriptor.kind == .filePreview)
        #expect(thumbnail.descriptor.fileName.hasSuffix(".png"))
        #expect(thumbnail.descriptor.pixelWidth > 0)
        #expect(thumbnail.descriptor.pixelHeight > 0)
        #expect(thumbnail.data.isEmpty == false)
    }

    @Test func normalizerAttachesImagePreviewThumbnailForImageFileReferences() throws {
        let root = try Self.makeTemporaryRoot()
        let fileURL = root.appending(path: "wide-image.png")
        let imageData = try #require(Self.makePNGData(size: NSSize(width: 640, height: 320)))
        try imageData.write(to: fileURL)
        let normalizer = ClipboardNormalizer()
        let snapshot = ClipboardPasteboardSnapshot(
            changeCount: 20,
            availableTypes: ["public.file-url"],
            dataByType: [:],
            fileURLs: [fileURL]
        )

        let optionalCapture = try normalizer.normalize(snapshot: snapshot, sourceApp: nil)
        let capture = try #require(optionalCapture)
        let thumbnail = try #require(capture.thumbnail)

        #expect(capture.contentType == .file)
        #expect(thumbnail.descriptor.kind == .imagePreview)
        #expect(thumbnail.descriptor.pixelWidth >= 300)
        #expect(thumbnail.descriptor.pixelHeight >= 150)
        #expect(thumbnail.data.isEmpty == false)
    }

    @Test func normalizerAttachesFolderThumbnailSnapshotForFolderReferences() throws {
        let root = try Self.makeTemporaryRoot()
        let folderURL = root.appending(path: "folder", directoryHint: .isDirectory)
        try FileManager.default.createDirectory(at: folderURL, withIntermediateDirectories: true)
        let normalizer = ClipboardNormalizer()
        let snapshot = ClipboardPasteboardSnapshot(
            changeCount: 18,
            availableTypes: ["public.file-url"],
            dataByType: [:],
            fileURLs: [folderURL]
        )

        let optionalCapture = try normalizer.normalize(snapshot: snapshot, sourceApp: nil)
        let capture = try #require(optionalCapture)
        let thumbnail = try #require(capture.thumbnail)

        #expect(capture.contentType == .file)
        #expect(thumbnail.descriptor.kind == .folderPreview)
        #expect(thumbnail.descriptor.fileName.hasSuffix(".png"))
        #expect(thumbnail.descriptor.pixelWidth > 0)
        #expect(thumbnail.descriptor.pixelHeight > 0)
        #expect(thumbnail.data.isEmpty == false)
    }

    @Test func pasteExecutorWritesOriginalPlainTextTypeBackToPasteboard() throws {
        let root = try Self.makeTemporaryRoot()
        let fileStore = LocalFileStore(baseURL: root)
        let settingsStore = try SettingsStore(
            storageURL: root.appending(path: "Settings/settings.json")
        )
        let store = try ClipboardStore(fileStore: fileStore)
        let history = try store.save(
            ClipboardCapture(
                contentType: .plainText,
                previewText: "hello",
                contentHash: "plain-hash",
                capturedAt: Date(),
                sourceAppBundleID: nil,
                sourceAppName: nil,
                payload: .inline(
                    data: Data("hello".utf8),
                    pasteboardType: "public.utf8-plain-text",
                    suggestedFileExtension: "txt"
                )
            ),
            maxItems: 10
        )
        let pasteboard = RecordingClipboardPasteboardClient()
        let executor = PasteExecutor(store: store, pasteboardClient: pasteboard)

        let ticket = try executor.write(item: history[0])

        #expect(ticket.contentHash == "plain-hash")
        #expect(pasteboard.lastWrittenTypes == ["public.utf8-plain-text"])
    }

    @Test func pasteExecutorWritesAllStoredFigmaRepresentationsBackToPasteboard() throws {
        let root = try Self.makeTemporaryRoot()
        let fileStore = LocalFileStore(baseURL: root)
        let settingsStore = try SettingsStore(
            storageURL: root.appending(path: "Settings/settings.json")
        )
        let store = try ClipboardStore(fileStore: fileStore)
        let history = try store.save(
            ClipboardCapture(
                contentType: .figmaText,
                previewText: "Button",
                contentHash: "figma-text-hash",
                capturedAt: Date(),
                sourceAppBundleID: "com.figma.Desktop",
                sourceAppName: "Figma",
                payload: .figma(
                    ClipboardFigmaPayload(
                        representations: [
                            ClipboardInlineRepresentation(
                                data: Data("<span data-meta=\"figma text\"></span>".utf8),
                                pasteboardType: "public.html",
                                suggestedFileExtension: "html"
                            ),
                            ClipboardInlineRepresentation(
                                data: Data("Button".utf8),
                                pasteboardType: "public.utf8-plain-text",
                                suggestedFileExtension: "txt"
                            ),
                            ClipboardInlineRepresentation(
                                data: Data("rfh-token".utf8),
                                pasteboardType: "org.chromium.internal.source-rfh-token",
                                suggestedFileExtension: nil
                            ),
                        ]
                    )
                )
            ),
            maxItems: 10
        )
        let reloaded = try store.loadHistory()
        let pasteboard = RecordingClipboardPasteboardClient()
        let executor = PasteExecutor(store: store, pasteboardClient: pasteboard)

        let ticket = try executor.write(item: reloaded[0])

        #expect(ticket.contentHash == "figma-text-hash")
        #expect(pasteboard.lastWrittenTypes == [
            "public.html",
            "public.utf8-plain-text",
            "org.chromium.internal.source-rfh-token",
        ])
        #expect(history.count == 1)
    }

    @Test func pasteExecutorFailsWhenFileReferenceTargetIsMissing() throws {
        let root = try Self.makeTemporaryRoot()
        let fileURL = root.appending(path: "missing.txt")
        try Data("gone".utf8).write(to: fileURL)
        let bookmark = try fileURL.bookmarkData(
            options: .minimalBookmark,
            includingResourceValuesForKeys: nil,
            relativeTo: nil
        )
        try FileManager.default.removeItem(at: fileURL)

        let item = ClipboardHistoryItem(
            id: UUID(),
            contentType: .file,
            previewText: "missing.txt",
            contentHash: "missing-file-hash",
            copiedAt: Date(),
            sourceAppBundleID: nil,
            sourceAppName: nil,
            payload: .fileReferences([
                ClipboardFileReference(
                    fileName: "missing.txt",
                    isDirectory: false,
                    bookmarkData: bookmark
                )
            ])
        )
        let store = try Self.makeClipboardStoreForTests(root: root)
        _ = try store.replaceHistory([item])
        let pasteboard = RecordingClipboardPasteboardClient()
        let executor = PasteExecutor(store: store, pasteboardClient: pasteboard)

        do {
            _ = try executor.write(item: item)
            Issue.record("Expected paste executor to fail for a missing file reference")
        } catch let error as NSError {
            #expect(error.domain == NSCocoaErrorDomain)
            #expect(error.code == NSFileNoSuchFileError)
        }
    }

    @Test func cleanupServiceRemovesExpiredItemsAndPayloadFiles() throws {
        let root = try Self.makeTemporaryRoot()
        let fileStore = LocalFileStore(baseURL: root)
        let settingsStore = try SettingsStore(
            storageURL: root.appending(path: "Settings/settings.json")
        )
        try settingsStore.update { settings in
            settings.clipboardAutoCleanupPolicy = .daily
        }
        let store = try ClipboardStore(fileStore: fileStore)
        let history = try store.save(
            ClipboardCapture(
                contentType: .plainText,
                previewText: "old",
                contentHash: "old-hash",
                capturedAt: Date(timeIntervalSince1970: 0),
                sourceAppBundleID: nil,
                sourceAppName: nil,
                payload: .inline(
                    data: Data("old".utf8),
                    pasteboardType: "public.utf8-plain-text",
                    suggestedFileExtension: "txt"
                )
            ),
            maxItems: 10
        )
        let cleanup = ClipboardCleanupService(
            store: store,
            settingsStore: settingsStore,
            scheduler: CleanupScheduler()
        )
        let payloadURL: URL
        switch history[0].payload {
        case let .inline(fileName, _, _):
            payloadURL = fileStore.url(for: .clipboardPayloads).appending(path: fileName)
        case .figma:
            Issue.record("Expected inline payload")
            return
        case .fileReferences:
            Issue.record("Expected inline payload")
            return
        }

        let result = try cleanup.runIfNeeded(now: Date(timeIntervalSince1970: 90_000))

        #expect(result.didRun == true)
        #expect(result.remainingCount == 0)
        #expect(try store.loadHistory().isEmpty)
        #expect(FileManager.default.fileExists(atPath: payloadURL.path(percentEncoded: false)) == false)
    }

    @Test func clipboardCoreStartsAndStopsPollingWithEnergyModes() throws {
        let core = try Self.makeClipboardCoreForRuntimeTests()

        core.energyModeDidChange(.backgroundCore)
        #expect(core.isPolling == true)

        core.energyModeDidChange(.suspended)
        #expect(core.isPolling == false)
    }

    @Test func persistentPollFailureIsReportedToDiagnosticsOnce() throws {
        let root = try Self.makeTemporaryRoot()
        // Block the Clipboard directory with a plain file so persisting any
        // capture fails — the shape of a disk-level storage failure.
        try Data().write(to: root.appending(path: "Clipboard"))
        let fileStore = LocalFileStore(baseURL: root)
        let settingsStore = try SettingsStore(
            storageURL: root.appending(path: "Settings/settings.json")
        )
        let store = try ClipboardStore(fileStore: fileStore)
        let pasteboard = ScriptedTextClipboardPasteboardClient()
        let cleanup = ClipboardCleanupService(
            store: store,
            settingsStore: settingsStore,
            scheduler: CleanupScheduler()
        )
        let executor = PasteExecutor(store: store, pasteboardClient: pasteboard)
        let diagnostics = DiagnosticsStore()
        let core = try ClipboardCore(
            pasteboardClient: pasteboard,
            sourceApplicationProvider: StubClipboardSourceApplicationProvider(),
            normalizer: ClipboardNormalizer(),
            store: store,
            settingsStore: settingsStore,
            cleanupService: cleanup,
            pasteExecutor: executor,
            diagnosticsStore: diagnostics
        )

        pasteboard.copy(text: "first capture")
        core.pollOnceReportingErrors()
        pasteboard.copy(text: "second capture")
        core.pollOnceReportingErrors()

        // Repeated failures collapse into one diagnostic until a poll succeeds
        // again — a 2 Hz poll must not flood the log.
        let errors = diagnostics.messages.filter { $0.severity == .error }
        #expect(errors.count == 1)
        #expect(errors.first?.message.contains("Clipboard capture failed") == true)
    }

    @Test func viewModelProjectsEmptyStateWhenHistoryIsMissing() throws {
        let core = try Self.makeClipboardCoreForRuntimeTests(initialHistory: [])
        let viewModel = ClipboardViewModel(core: core)

        viewModel.refresh()

        #expect(viewModel.isEmpty == true)
        #expect(viewModel.cards.isEmpty)
    }

    @Test func viewModelProjectsLatestItemsIntoCardsWithoutCollapsingPanel() throws {
        let core = try Self.makeClipboardCoreForRuntimeTests(
            initialHistory: [
                ClipboardHistoryItem(
                    id: UUID(),
                    contentType: .plainText,
                    previewText: "alpha",
                    contentHash: "alpha-hash",
                    copiedAt: Date(timeIntervalSince1970: 20),
                    sourceAppBundleID: "com.apple.TextEdit",
                    sourceAppName: "TextEdit",
                    payload: .inline(
                        fileName: "alpha.payload",
                        pasteboardType: "public.utf8-plain-text",
                        suggestedFileExtension: "txt"
                    )
                )
            ]
        )
        let viewModel = ClipboardViewModel(core: core)

        viewModel.refresh()

        #expect(viewModel.cards.count == 1)
        #expect(viewModel.cards[0].previewText == "alpha")
        #expect(viewModel.cards[0].previewState == .textOnly)
        #expect(viewModel.cards[0].sourceAppBundleID == "com.apple.TextEdit")
        #expect(viewModel.cards[0].sourceAppName == "TextEdit")
        #expect(viewModel.lastPasteError == nil)
    }

    @Test func clipboardRelativeTimeTextUsesDiscreteChineseBuckets() {
        let now = Date(timeIntervalSince1970: 1_000_000)

        #expect(ClipboardViewModel.relativeTimeText(for: now.addingTimeInterval(-30), relativeTo: now) == "现在")
        #expect(ClipboardViewModel.relativeTimeText(for: now.addingTimeInterval(-9 * 60), relativeTo: now) == "9 分钟前")
        #expect(ClipboardViewModel.relativeTimeText(for: now.addingTimeInterval(-12 * 60), relativeTo: now) == "15 分钟前")
        #expect(ClipboardViewModel.relativeTimeText(for: now.addingTimeInterval(-35 * 60), relativeTo: now) == "半小时前")
        #expect(ClipboardViewModel.relativeTimeText(for: now.addingTimeInterval(-4 * 3600), relativeTo: now) == "4 小时前")
        #expect(ClipboardViewModel.relativeTimeText(for: now.addingTimeInterval(-13 * 3600), relativeTo: now) == "半天前")
        #expect(ClipboardViewModel.relativeTimeText(for: now.addingTimeInterval(-6 * 86_400), relativeTo: now) == "6 天前")
        #expect(ClipboardViewModel.relativeTimeText(for: now.addingTimeInterval(-18 * 86_400), relativeTo: now) == "两周前")
        #expect(ClipboardViewModel.relativeTimeText(for: now.addingTimeInterval(-45 * 86_400), relativeTo: now) == "一个月前")
        #expect(ClipboardViewModel.relativeTimeText(for: now.addingTimeInterval(-170 * 86_400), relativeTo: now) == "五个月前")
        #expect(ClipboardViewModel.relativeTimeText(for: now.addingTimeInterval(-240 * 86_400), relativeTo: now) == "半年前")
        #expect(ClipboardViewModel.relativeTimeText(for: now.addingTimeInterval(-400 * 86_400), relativeTo: now) == "一年前")
        #expect(ClipboardViewModel.relativeTimeText(for: now.addingTimeInterval(-900 * 86_400), relativeTo: now) == "更久")
    }

    @Test func compactClipboardLayoutMatchesContentLayerDesignMetrics() {
        #expect(ClipboardModuleLayout.listSurfaceHeight == 116)
        #expect(ClipboardModuleLayout.emptySurfaceHeight == 56)
        #expect(ClipboardModuleLayout.successSurfaceHeight == 56)
        #expect(ClipboardModuleLayout.panelBodySize(isEmpty: false) == CGSize(width: 580, height: 177))
        #expect(ClipboardModuleLayout.panelBodySize(isEmpty: true) == CGSize(width: 580, height: 120))
        #expect(ClipboardModuleLayout.successPanelBodySize == CGSize(width: 580, height: 120))
        #expect(ClipboardModuleLayout.surfaceFillOpacity == 0)
        #expect(ClipboardModuleLayout.usesHostSurfaceStroke == true)
        #expect(ClipboardModuleLayout.listInsetHorizontal == 7)
        #expect(ClipboardModuleLayout.listInsetTop == 4)
        #expect(ClipboardCardLayout.cardSize == CGSize(width: 96, height: 108))
        #expect(ClipboardCardLayout.previewSize == CGSize(width: 76, height: 70))
        #expect(ClipboardCardLayout.cardSpacing == 4)
        #expect(ClipboardCardLayout.cardPadding == CGSize(width: 10, height: 8))
        #expect(ClipboardCardLayout.cardCornerRadius == 22)
    }

    @Test func verticalWheelScrollMapsIntoHorizontalOffset() {
        let mappedOffset = ClipboardWheelScrollMapper.targetOffset(
            currentOffset: 20,
            viewportWidth: 536,
            contentWidth: 960,
            deltaX: 0,
            deltaY: -48
        )

        #expect(mappedOffset == 68)
    }

    @Test func wheelScrollMappingClampsToHorizontalBounds() {
        let mappedOffset = ClipboardWheelScrollMapper.targetOffset(
            currentOffset: 420,
            viewportWidth: 536,
            contentWidth: 960,
            deltaX: 0,
            deltaY: -80
        )

        #expect(mappedOffset == 424)
    }

    @Test func horizontalDominantWheelInputKeepsNativeScrollBehavior() {
        let mappedOffset = ClipboardWheelScrollMapper.targetOffset(
            currentOffset: 20,
            viewportWidth: 536,
            contentWidth: 960,
            deltaX: 30,
            deltaY: -12
        )

        #expect(mappedOffset == nil)
    }

    @Test func viewModelProjectsMissingReferenceBadgeState() throws {
        let root = try Self.makeTemporaryRoot()
        let fileStore = LocalFileStore(baseURL: root)
        let missingReference = try Self.makeMissingReference(named: "missing-file.txt", in: root)
        let thumbnailURL = try Self.writeThumbnailFile(
            named: "missing-file-thumbnail.png",
            fileStore: fileStore
        )
        let item = ClipboardHistoryItem(
            id: UUID(),
            contentType: .file,
            previewText: "missing-file.txt",
            contentHash: "missing-reference-hash",
            copiedAt: Date(timeIntervalSince1970: 30),
            sourceAppBundleID: nil,
            sourceAppName: "Finder",
            payload: .fileReferences([missingReference]),
            thumbnail: ClipboardThumbnailDescriptor(
                fileName: thumbnailURL.lastPathComponent,
                pixelWidth: 96,
                pixelHeight: 96,
                kind: .filePreview
            )
        )
        let core = try Self.makeClipboardCoreForRuntimeTests(
            initialHistory: [item],
            root: root
        )
        let viewModel = ClipboardViewModel(core: core, localFileStore: fileStore)

        viewModel.refresh()

        let card = try #require(viewModel.cards.first)
        let thumbnail: ClipboardCardThumbnail
        switch card.previewState {
        case let .thumbnailWithMissingReference(projectedThumbnail):
            thumbnail = projectedThumbnail
        default:
            Issue.record("Expected thumbnailWithMissingReference preview state")
            return
        }

        #expect(viewModel.cards.count == 1)
        #expect(thumbnail.url == thumbnailURL)
        #expect(thumbnail.kind == ClipboardThumbnailKind.filePreview)
        #expect(card.isPastebackSupported)
    }

    @Test func viewModelProjectsMissingReferencePlaceholderWhenThumbnailFileIsMissing() throws {
        let root = try Self.makeTemporaryRoot()
        let fileStore = LocalFileStore(baseURL: root)
        let missingReference = try Self.makeMissingReference(named: "missing-folder", in: root)
        let item = ClipboardHistoryItem(
            id: UUID(),
            contentType: .file,
            previewText: "missing-folder",
            contentHash: "missing-placeholder-hash",
            copiedAt: Date(timeIntervalSince1970: 40),
            sourceAppBundleID: nil,
            sourceAppName: "Finder",
            payload: .fileReferences([missingReference]),
            thumbnail: ClipboardThumbnailDescriptor(
                fileName: "missing-folder-thumbnail.png",
                pixelWidth: 96,
                pixelHeight: 96,
                kind: .folderPreview
            )
        )
        let core = try Self.makeClipboardCoreForRuntimeTests(
            initialHistory: [item],
            root: root
        )
        let viewModel = ClipboardViewModel(core: core, localFileStore: fileStore)

        viewModel.refresh()

        #expect(viewModel.cards.count == 1)
        #expect(viewModel.cards[0].previewState == ClipboardCardPreviewState.missingReferencePlaceholder)
        #expect(viewModel.cards[0].isPastebackSupported)
    }

    @Test func viewModelProjectsThumbnailStateForInlineImageHistory() throws {
        let root = try Self.makeTemporaryRoot()
        let fileStore = LocalFileStore(baseURL: root)
        let thumbnailURL = try Self.writeThumbnailFile(
            named: "inline-image-thumbnail.png",
            fileStore: fileStore
        )
        let item = ClipboardHistoryItem(
            id: UUID(),
            contentType: .image,
            previewText: "Screenshot",
            contentHash: "inline-image-hash",
            copiedAt: Date(timeIntervalSince1970: 50),
            sourceAppBundleID: nil,
            sourceAppName: "Preview",
            payload: .inline(
                fileName: "inline-image.payload",
                pasteboardType: "public.png",
                suggestedFileExtension: "png"
            ),
            thumbnail: ClipboardThumbnailDescriptor(
                fileName: thumbnailURL.lastPathComponent,
                pixelWidth: 128,
                pixelHeight: 72,
                kind: .imagePreview
            )
        )
        let core = try Self.makeClipboardCoreForRuntimeTests(
            initialHistory: [item],
            root: root
        )
        let viewModel = ClipboardViewModel(core: core, localFileStore: fileStore)

        viewModel.refresh()

        let card = try #require(viewModel.cards.first)
        let thumbnail: ClipboardCardThumbnail
        switch card.previewState {
        case let .thumbnail(projectedThumbnail):
            thumbnail = projectedThumbnail
        default:
            Issue.record("Expected thumbnail preview state")
            return
        }

        #expect(viewModel.cards.count == 1)
        #expect(thumbnail.url == thumbnailURL)
        #expect(thumbnail.kind == ClipboardThumbnailKind.imagePreview)
        #expect(card.isPastebackSupported)
    }

    @Test func viewModelPasteSurfacesMissingReferenceErrorForQuestionMarkCards() throws {
        let root = try Self.makeTemporaryRoot()
        let fileStore = LocalFileStore(baseURL: root)
        let missingReference = try Self.makeMissingReference(named: "missing-paste.txt", in: root)
        let thumbnailURL = try Self.writeThumbnailFile(
            named: "missing-paste-thumbnail.png",
            fileStore: fileStore
        )
        let item = ClipboardHistoryItem(
            id: UUID(),
            contentType: .file,
            previewText: "missing-paste.txt",
            contentHash: "missing-paste-hash",
            copiedAt: Date(timeIntervalSince1970: 60),
            sourceAppBundleID: nil,
            sourceAppName: "Finder",
            payload: .fileReferences([missingReference]),
            thumbnail: ClipboardThumbnailDescriptor(
                fileName: thumbnailURL.lastPathComponent,
                pixelWidth: 96,
                pixelHeight: 96,
                kind: .filePreview
            )
        )
        let core = try Self.makeClipboardCoreForRuntimeTests(
            initialHistory: [item],
            root: root
        )
        let viewModel = ClipboardViewModel(core: core, localFileStore: fileStore)
        var callbackCount = 0

        viewModel.refresh()
        viewModel.paste(itemID: item.id) {
            callbackCount += 1
        }

        #expect(callbackCount == 0)
        #expect(viewModel.lastPasteError == "原文件已不存在，无法重新放回剪贴板。")
        #expect(viewModel.cards.first?.isPastebackSupported == true)
    }

    @Test func clipboardCorePastePromotesSelectedHistoryItemToFront() throws {
        let root = try Self.makeTemporaryRoot()
        let fileStore = LocalFileStore(baseURL: root)
        let settingsStore = try SettingsStore(
            storageURL: root.appending(path: "Settings/settings.json")
        )
        let store = try ClipboardStore(fileStore: fileStore)
        let firstHistory = try store.save(
            ClipboardCapture(
                contentType: .plainText,
                previewText: "first",
                contentHash: "first-hash",
                capturedAt: Date(timeIntervalSince1970: 10),
                sourceAppBundleID: nil,
                sourceAppName: nil,
                payload: .inline(
                    data: Data("first".utf8),
                    pasteboardType: "public.utf8-plain-text",
                    suggestedFileExtension: "txt"
                )
            ),
            maxItems: 10
        )
        let secondHistory = try store.save(
            ClipboardCapture(
                contentType: .plainText,
                previewText: "second",
                contentHash: "second-hash",
                capturedAt: Date(timeIntervalSince1970: 20),
                sourceAppBundleID: nil,
                sourceAppName: nil,
                payload: .inline(
                    data: Data("second".utf8),
                    pasteboardType: "public.utf8-plain-text",
                    suggestedFileExtension: "txt"
                )
            ),
            maxItems: 10
        )
        let originalFirstItem = try #require(firstHistory.first)
        let targetItem = try #require(
            secondHistory.first(where: { $0.contentHash == "first-hash" })
        )
        let pasteboard = RecordingClipboardPasteboardClient()
        let cleanup = ClipboardCleanupService(
            store: store,
            settingsStore: settingsStore,
            scheduler: CleanupScheduler()
        )
        let executor = PasteExecutor(store: store, pasteboardClient: pasteboard)
        let core = try ClipboardCore(
            pasteboardClient: pasteboard,
            sourceApplicationProvider: StubClipboardSourceApplicationProvider(),
            normalizer: ClipboardNormalizer(),
            store: store,
            settingsStore: settingsStore,
            cleanupService: cleanup,
            pasteExecutor: executor
        )
        let promotedBefore = Date()

        try core.paste(item: targetItem)

        #expect(core.history.first?.id == originalFirstItem.id)
        #expect(core.history.first?.contentHash == "first-hash")
        #expect(core.history.dropFirst().first?.contentHash == "second-hash")
        #expect(core.history.first?.copiedAt ?? .distantPast >= promotedBefore)
    }

    @Test func viewModelPasteEntersExpandedSuccessPhaseThenDelaysCollapseCallback() throws {
        let root = try Self.makeTemporaryRoot()
        let fileStore = LocalFileStore(baseURL: root)
        let settingsStore = try SettingsStore(
            storageURL: root.appending(path: "Settings/settings.json")
        )
        let store = try ClipboardStore(fileStore: fileStore)
        _ = try store.save(
            ClipboardCapture(
                contentType: .plainText,
                previewText: "first",
                contentHash: "first-hash",
                capturedAt: Date(timeIntervalSince1970: 10),
                sourceAppBundleID: nil,
                sourceAppName: nil,
                payload: .inline(
                    data: Data("first".utf8),
                    pasteboardType: "public.utf8-plain-text",
                    suggestedFileExtension: "txt"
                )
            ),
            maxItems: 10
        )
        let history = try store.save(
            ClipboardCapture(
                contentType: .plainText,
                previewText: "second",
                contentHash: "second-hash",
                capturedAt: Date(timeIntervalSince1970: 20),
                sourceAppBundleID: nil,
                sourceAppName: nil,
                payload: .inline(
                    data: Data("second".utf8),
                    pasteboardType: "public.utf8-plain-text",
                    suggestedFileExtension: "txt"
                )
            ),
            maxItems: 10
        )
        let targetItem = try #require(history.first(where: { $0.contentHash == "first-hash" }))
        let pasteboard = RecordingClipboardPasteboardClient()
        let cleanup = ClipboardCleanupService(
            store: store,
            settingsStore: settingsStore,
            scheduler: CleanupScheduler()
        )
        let executor = PasteExecutor(store: store, pasteboardClient: pasteboard)
        let core = try ClipboardCore(
            pasteboardClient: pasteboard,
            sourceApplicationProvider: StubClipboardSourceApplicationProvider(),
            normalizer: ClipboardNormalizer(),
            store: store,
            settingsStore: settingsStore,
            cleanupService: cleanup,
            pasteExecutor: executor
        )
        let scheduler = ManualClipboardDelayScheduler()
        let viewModel = ClipboardViewModel(
            core: core,
            successPhaseDuration: Duration.seconds(2),
            postCollapseResetDelay: Duration.milliseconds(250),
            delayScheduler: scheduler.schedule(after:action:)
        )
        var callbackCount = 0

        viewModel.refresh()
        viewModel.paste(itemID: targetItem.id) {
            callbackCount += 1
        }

        #expect(callbackCount == 0)
        #expect(viewModel.lastPasteError == nil)
        #expect(viewModel.phase == .pastebackSuccess)
        #expect(viewModel.cards.map(\.previewText) == ["first", "second"])
        #expect(viewModel.cards.first?.id == targetItem.id)
        #expect(scheduler.scheduledDurations == [Duration.seconds(2)])

        scheduler.runNext()

        #expect(callbackCount == 1)
        #expect(viewModel.phase == .pastebackSuccess)
        #expect(scheduler.scheduledDurations == [Duration.seconds(2), Duration.milliseconds(250)])

        scheduler.runNext()

        #expect(viewModel.phase == .history)
    }

    @Test func viewModelPasteSetsExplicitErrorWhenItemIsMissing() throws {
        let core = try Self.makeClipboardCoreForRuntimeTests()
        let viewModel = ClipboardViewModel(core: core)
        var callbackCount = 0

        viewModel.refresh()
        viewModel.paste(itemID: UUID()) {
            callbackCount += 1
        }

        #expect(callbackCount == 0)
        #expect(viewModel.lastPasteError == "该候选内容已不可用，请重新复制后再试。")
        #expect(viewModel.isEmpty)
    }

    @Test func viewModelPasteSetsFriendlyErrorWhenPastebackFails() throws {
        let root = try Self.makeTemporaryRoot()
        let fileStore = LocalFileStore(baseURL: root)
        let settingsStore = try SettingsStore(
            storageURL: root.appending(path: "Settings/settings.json")
        )
        let store = try ClipboardStore(fileStore: fileStore)
        let history = try store.save(
            ClipboardCapture(
                contentType: .plainText,
                previewText: "alpha",
                contentHash: "alpha-hash",
                capturedAt: Date(timeIntervalSince1970: 10),
                sourceAppBundleID: nil,
                sourceAppName: nil,
                payload: .inline(
                    data: Data("alpha".utf8),
                    pasteboardType: "public.utf8-plain-text",
                    suggestedFileExtension: "txt"
                )
            ),
            maxItems: 10
        )
        let targetItem = try #require(history.first)
        let pasteboard = FailingClipboardPasteboardClient(
            writeError: NSError(domain: "ClipboardModuleTests", code: 7)
        )
        let cleanup = ClipboardCleanupService(
            store: store,
            settingsStore: settingsStore,
            scheduler: CleanupScheduler()
        )
        let executor = PasteExecutor(store: store, pasteboardClient: pasteboard)
        let core = try ClipboardCore(
            pasteboardClient: pasteboard,
            sourceApplicationProvider: StubClipboardSourceApplicationProvider(),
            normalizer: ClipboardNormalizer(),
            store: store,
            settingsStore: settingsStore,
            cleanupService: cleanup,
            pasteExecutor: executor
        )
        let viewModel = ClipboardViewModel(core: core)
        var callbackCount = 0

        viewModel.refresh()
        viewModel.paste(itemID: targetItem.id) {
            callbackCount += 1
        }

        #expect(callbackCount == 0)
        #expect(viewModel.lastPasteError == "放回剪贴板失败，请重试。")
        #expect(viewModel.cards.map(\.previewText) == ["alpha"])
    }

    @Test func clipboardSettingsViewModelPersistsMaxItemsAndCleanupPolicy() throws {
        let root = try Self.makeTemporaryRoot()
        let settingsStore = try SettingsStore(
            storageURL: root.appending(path: "Settings/settings.json")
        )
        let viewModel = ClipboardSettingsViewModel(settingsStore: settingsStore)

        try viewModel.updateMaxItems(50)
        try viewModel.updateCleanupPolicy(.weekly)

        #expect(settingsStore.settings.clipboardMaxItems == 50)
        #expect(settingsStore.settings.clipboardAutoCleanupPolicy == .weekly)
    }

    private static func makeTemporaryRoot() throws -> URL {
        let url = FileManager.default.temporaryDirectory
            .appending(path: "ClipboardModuleTests")
            .appending(path: UUID().uuidString)
        try FileManager.default.createDirectory(at: url, withIntermediateDirectories: true)
        return url
    }

    private static func makeClipboardStoreForTests(root: URL) throws -> ClipboardStore {
        let fileStore = LocalFileStore(baseURL: root)
        let settingsStore = try SettingsStore(
            storageURL: root.appending(path: "Settings/settings.json")
        )
        return try ClipboardStore(fileStore: fileStore)
    }

    private static func makePNGData(size: NSSize) -> Data? {
        let image = NSImage(size: size)
        image.lockFocus()
        NSColor.systemBlue.setFill()
        NSBezierPath(rect: NSRect(origin: .zero, size: size)).fill()
        image.unlockFocus()

        guard
            let tiffData = image.tiffRepresentation,
            let representation = NSBitmapImageRep(data: tiffData)
        else {
            return nil
        }

        return representation.representation(using: .png, properties: [:])
    }

    private static func makeClipboardCoreForRuntimeTests(
        initialHistory: [ClipboardHistoryItem] = [],
        root: URL? = nil
    ) throws -> ClipboardCore {
        let root = try root ?? makeTemporaryRoot()
        let store = try makeClipboardStoreForTests(root: root)
        let settingsStore = try SettingsStore(
            storageURL: root.appending(path: "Settings/settings.json")
        )
        _ = try store.replaceHistory(initialHistory)
        let pasteboard = RecordingClipboardPasteboardClient()
        let cleanup = ClipboardCleanupService(
            store: store,
            settingsStore: settingsStore,
            scheduler: CleanupScheduler()
        )
        let executor = PasteExecutor(store: store, pasteboardClient: pasteboard)

        return try ClipboardCore(
            pasteboardClient: pasteboard,
            sourceApplicationProvider: StubClipboardSourceApplicationProvider(),
            normalizer: ClipboardNormalizer(),
            store: store,
            settingsStore: settingsStore,
            cleanupService: cleanup,
            pasteExecutor: executor
        )
    }

    private static func makeMissingReference(named name: String, in root: URL) throws -> ClipboardFileReference {
        let fileURL = root.appending(path: name)
        try Data(name.utf8).write(to: fileURL)
        let bookmarkData = try fileURL.bookmarkData(
            options: .minimalBookmark,
            includingResourceValuesForKeys: nil,
            relativeTo: nil
        )
        try FileManager.default.removeItem(at: fileURL)

        return ClipboardFileReference(
            fileName: name,
            isDirectory: false,
            bookmarkData: bookmarkData
        )
    }

    @discardableResult
    private static func writeThumbnailFile(
        named fileName: String,
        fileStore: LocalFileStore
    ) throws -> URL {
        let directoryURL = try fileStore.prepareDirectory(.clipboardThumbnails)
        let thumbnailURL = directoryURL.appending(path: fileName)
        let data = try #require(makePNGData(size: NSSize(width: 32, height: 24)))
        try data.write(to: thumbnailURL, options: [.atomic])
        return thumbnailURL
    }
}

private extension ResolvedRestPresentation {
    var activeRequest: RestVariantRequest? {
        switch self {
        case .none:
            nil
        case .request(let request):
            request
        }
    }
}

@MainActor
private final class ManualClipboardDelayScheduler {
    private(set) var scheduledDurations: [Duration] = []
    private var actions: [() -> Void] = []

    func schedule(
        after delay: Duration,
        action: @escaping @MainActor () -> Void
    ) -> Task<Void, Never> {
        scheduledDurations.append(delay)
        actions.append(action)
        return Task {}
    }

    func runNext() {
        guard actions.isEmpty == false else {
            Issue.record("Expected scheduled delay action")
            return
        }

        let action = actions.removeFirst()
        action()
    }
}

@MainActor
private final class RecordingClipboardPasteboardClient: ClipboardPasteboardClient {
    var changeCount: Int = 0
    var lastWrittenTypes: [String] = []

    func snapshot() -> ClipboardPasteboardSnapshot {
        ClipboardPasteboardSnapshot(
            changeCount: changeCount,
            availableTypes: [],
            dataByType: [:],
            fileURLs: []
        )
    }

    func write(items: [NSPasteboardItem]) throws {
        lastWrittenTypes = items.flatMap { item in
            item.types.map(\.rawValue)
        }
        changeCount += 1
    }
}

@MainActor
private final class ScriptedTextClipboardPasteboardClient: ClipboardPasteboardClient {
    private(set) var changeCount: Int = 0
    private var text = ""

    func copy(text: String) {
        self.text = text
        changeCount += 1
    }

    func snapshot() -> ClipboardPasteboardSnapshot {
        ClipboardPasteboardSnapshot(
            changeCount: changeCount,
            availableTypes: ["public.utf8-plain-text"],
            dataByType: ["public.utf8-plain-text": Data(text.utf8)],
            fileURLs: []
        )
    }

    func write(items: [NSPasteboardItem]) throws {}
}

@MainActor
private final class FailingClipboardPasteboardClient: ClipboardPasteboardClient {
    let writeError: Error
    var changeCount: Int = 0

    init(writeError: Error) {
        self.writeError = writeError
    }

    func snapshot() -> ClipboardPasteboardSnapshot {
        ClipboardPasteboardSnapshot(
            changeCount: changeCount,
            availableTypes: [],
            dataByType: [:],
            fileURLs: []
        )
    }

    func write(items: [NSPasteboardItem]) throws {
        throw writeError
    }
}

private struct StubClipboardSourceApplicationProvider: ClipboardSourceApplicationProviding {
    func currentSourceApplication() -> ClipboardSourceApplication? {
        nil
    }
}
